site_name: UAB Research Computing
repo_url: https://github.com/uabrc/researcher-facing-MkDocs

theme:
  name: material
  include_search_page: true
  search_index_only: true
  feature:
    tabs: true
  custom_dir: theme

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2021-2022 The University of Alabama at Birmingham.<br /><b>Still stuck after reading?</b> Email us at <a href="mailto:support@listserv.uab.edu" class="supportemail">support@listserv.uab.edu</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false
  - toc:
      permalink: true

plugins:
  - search
  - table-reader:
      data_path: docs

nav:
  - Home: index.md
  - Welcome:
      - welcome/welcome.md
      - welcome/rc_days.md
  - Account Management:
      - account_management/uab_researcher.md
      - External Collaborators (XIAS):
          - account_management/xias_users.md
          - account_management/xias_sites.md
          - account_management/xias_guest.md
      - account_management/gitlab_researcher.md
  - Data Management:
      - data_management/storage.md
      - data_management/s3.md
      - File Transfer:
          - data_management/transfer/globus.md
          - data_management/transfer/rclone.md
          - data_management/transfer/filezilla.md
  - Cheaha User Guide:
      - Getting Started: cheaha/getting_started.md
      - Hardware: cheaha/hardware.md
      - Open OnDemand:
          - cheaha/open_ondemand/ood_main.md
          - cheaha/open_ondemand/ood_interactive.md
          - cheaha/open_ondemand/ood_files.md
          - cheaha/open_ondemand/ood_jobs.md
      - SLURM:
          - Introduction: cheaha/slurm/introduction.md
          - cheaha/slurm/sbatch_usage.md
          - cheaha/slurm/gpu.md
          - cheaha/slurm/job_management.md
      - cheaha/lmod.md
      - cheaha/conda.md
  - UAB Cloud:
      - Introduction: uab_cloud/introduction.md
      - Setup:
        - uab_cloud/network_setup_basic.md
        - uab_cloud/security_setup_basic.md
        - uab_cloud/instance_setup_basic.md
        - uab_cloud/volume_setup_basic.md
      - uab_cloud/cloud_remote_access.md
      - uab_cloud/installing_software.md
      - uab_cloud/snapshots.md
  - Help:
      - help/support.md
      - help/faq.md
